/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alex96.sincronizacostos.views;

import Controllers.ControllerPrincipal;
import com.alex96.sincronizacostos.utils.HeadersTable;
import com.alex96.sincronizacostos.utils.PaintRowTable;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author alefl
 */
public class Principal extends javax.swing.JFrame {
    private DefaultTableModel modelTable;
    private ControllerPrincipal cp;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setConfigWindow();
        setLookAndFeel();
        setDateSelector();
        setTable();
        setIniComponents();
    }
    
    private void setConfigWindow() {
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Sincronizador de Costos");
        this.getContentPane().setBackground(new Color(247, 247, 247));
    }
    
    private void setLookAndFeel() {
        try {
            this.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setDateSelector() {
        selectDate.setDate(new Date());
    }
    
    private void setIniComponents() {
        btnSincroniza.setEnabled(false);
        cp = new ControllerPrincipal(modelTable, tableMovimientos);
    }
    
    
    private void setTable() {
        // tableMovimientos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableMovimientos.setDefaultRenderer(Object.class, new PaintRowTable());
        modelTable = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelTable.addColumn("Documento");
        modelTable.addColumn("Referencia");
        modelTable.addColumn("Nombre Tercero");
        modelTable.addColumn("Articulos");
        modelTable.addColumn("Almacen");
        modelTable.addColumn("Fecha");
        modelTable.addColumn("Hora");
        modelTable.addColumn(" ");
        
        tableMovimientos.setModel(modelTable);
        
        JTableHeader headerTable = tableMovimientos.getTableHeader();
        headerTable.setDefaultRenderer(new HeadersTable());
        tableMovimientos.setTableHeader(headerTable);
        
        tableMovimientos.setRowHeight(30);
        tableMovimientos.getColumnModel().getColumn(0).setPreferredWidth(60); // Documento
        tableMovimientos.getColumnModel().getColumn(1).setPreferredWidth(60); // Referencia
        tableMovimientos.getColumnModel().getColumn(2).setPreferredWidth(300); // Nombre Tercero
        tableMovimientos.getColumnModel().getColumn(3).setPreferredWidth(50); // Articulos
        tableMovimientos.getColumnModel().getColumn(4).setPreferredWidth(200); // Almacen
        tableMovimientos.getColumnModel().getColumn(5).setPreferredWidth(70); // Fecha
        tableMovimientos.getColumnModel().getColumn(6).setPreferredWidth(70); // Hora
        tableMovimientos.getColumnModel().getColumn(7).setPreferredWidth(30); // Acciones
        
        tableMovimientos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = tableMovimientos.getColumnModel().getColumnIndexAtX(e.getX());
                int columns = tableMovimientos.getColumnCount();
                int row = e.getY() / tableMovimientos.getRowHeight();
                int rows = tableMovimientos.getRowCount();
                if (column <= columns && column >= 0 && row <= rows && row >= 0) {
                    Object contentRow = tableMovimientos.getValueAt(row, column);
                    if (contentRow instanceof JButton)
                        ((JButton) contentRow).doClick();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectDate = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        btnSincroniza = new javax.swing.JButton();
        btnLoadMovimientos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovimientos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuAcciones = new javax.swing.JMenu();
        menuItemCargar = new javax.swing.JMenuItem();
        menuItemSincronizar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sincronizador de Costos");

        selectDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectDatePropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Sincronizar Costos del dia:");

        labelFecha.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSincroniza.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSincroniza.setText("Sincronizar");

        btnLoadMovimientos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLoadMovimientos.setText("Cargar Movimientos");
        btnLoadMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadMovimientosActionPerformed(evt);
            }
        });

        tableMovimientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Referencia", "Nombre Tercero", "Articulos", "Almacen", "Fecha", "Hora"
            }
        ));
        jScrollPane1.setViewportView(tableMovimientos);

        menuArchivo.setText("Archivo");

        menuItemSalir.setText("Salir");
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuAcciones.setText("Acciones");

        menuItemCargar.setText("Cargar Movimientos");
        menuAcciones.add(menuItemCargar);

        menuItemSincronizar.setText("Sincronizar Costos");
        menuAcciones.add(menuItemSincronizar);

        jMenuBar1.add(menuAcciones);

        menuAyuda.setText("Ayuda");

        menuItemAyuda.setText("Ayuda");
        menuAyuda.add(menuItemAyuda);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSincroniza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(btnLoadMovimientos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSincroniza)
                            .addComponent(btnLoadMovimientos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectDatePropertyChange
        if (evt.getOldValue() != null) {
            SimpleDateFormat sd = new SimpleDateFormat("dd/MM/YYYY");
            labelFecha.setText(sd.format(selectDate.getCalendar().getTime()));
        }
    }//GEN-LAST:event_selectDatePropertyChange

    private void btnLoadMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadMovimientosActionPerformed
        if (selectDate != null) {
            SimpleDateFormat sd = new SimpleDateFormat("YYYYMMdd");
            cp.loadTable(sd.format(selectDate.getCalendar().getTime()));
        }
    }//GEN-LAST:event_btnLoadMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadMovimientos;
    private javax.swing.JButton btnSincroniza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuItemAyuda;
    private javax.swing.JMenuItem menuItemCargar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemSincronizar;
    private com.toedter.calendar.JCalendar selectDate;
    private javax.swing.JTable tableMovimientos;
    // End of variables declaration//GEN-END:variables
}
